feat: HS-188: Building before committing and added release rules

diff --git a/.husky/prepare-commit-msg b/.husky/prepare-commit-msg
--- a/.husky/prepare-commit-msg
+++ b/.husky/prepare-commit-msg
@@ -14,6 +14,16 @@ then
 fi
 echo "***** ReScript Code Compiled! *****"
 
+# JS Code Build
+echo "*****~~~~~ Checking ReScript Build ~~~~~~*****"
+if (! npm run build)
+then
+    echo
+    echo "*****~~~~~ ReScript Build Completition Failed! ~~~~~*****"
+    exit 1
+fi
+echo "***** ReScript Build Completed! *****"
+
 #Trailing Space Check
 echo "Evaluating for trailing spaces"
 
